Checkbox, Tab, Tabs, ToggleGroup, Toggle 컴포넌트 추가
hang-log-design-system/design-system pull request #2
Opened 2023-07-07 12:45 UTC by dladncks1217

2023-07-07 14:09 UTC, ashleysyheo requested changes
#### 절대 경로

지금 파일들에서 상대 경로나 제대로 되지 않은 절대 경로(i.e. `@/styles/Theme`)로 설정된 경우들이 있어요. 한 번 확인 부탁드립니다!

#### 타입 임포트

타입으로만 사용되는 임포트(?)들은 앞에 타입 온리 임포트해 주세요.

#### Tab & Toggle
하나만 클릭 된다는 것을 컴포넌트가 지금 확인할 수는 없는 거죠? 로직을 컴포넌트에서 안 갖고 있는 것도 괜찮고, 그런데 또 저런 컴포넌트만의 고유한 특성(?)은 살려야 할 것 같고... 어렵네요. 이 부분에 대해서는 어떻게 생각하세요?

진짜 진짜 진짜 진짜 수고 많았습니다!!! 💯

2023-07-08 04:17 UTC, dladncks1217 reviewed
> Tab & Toggle
하나만 클릭 된다는 것을 컴포넌트가 지금 확인할 수는 없는 거죠? 로직을 컴포넌트에서 안 갖고 있는 것도 괜찮고, 그런데 또 저런 컴포넌트만의 고유한 특성(?)은 살려야 할 것 같고... 어렵네요. 이 부분에 대해서는 어떻게 생각하세요?

저도 계속 고민하던 부분이고, 당장은 확인할 수 없습니다. 🥲 
컴포넌트만의 고유한 특성을 유지하고 싶었는데, 그럼 디자인시스템 특성상 최대한 추상화되어야 한다는 점이 어렵다고 판단했습니다... 복잡도가 너무 올라가서, 오히려 배포 후 사용하는데 어려움이 있을 수도 있겠다는 생각이 들더라구요.
당장은 이렇게 해보고 긍정적인 방향으로 점차 고도화 해 나가는건 어떨까요?

> 진짜 진짜 진짜 진짜 수고 많았습니다!!! 💯
꼼꼼한 코드리뷰 감사합니다~!🙌
애슐리도 고생 많으셨어요 👍

2023-07-08 04:17 UTC, dladncks1217 commented on src/stories/Tabs.stories.tsx
> +export const Playground: Story = {};
그러게요 Playground는 지워도 되겠군요😅 반영하겠습니다~!

2023-07-08 04:17 UTC, dladncks1217 commented on src/stories/ToggleGroup.stories.tsx
> +            <Toggle text="haha" selected />
css 반영이 양 끝과 가운데가 조금씩 달라서 함께 보여야 할 것 같아 select가 3개였습니다 ㅋㅋㅋ
생각해보니 하나만 보여줘도 될 것 같군요.
반영하겠습니다👍

2023-07-08 04:17 UTC, dladncks1217 commented on src/stories/Tabs.stories.tsx
> +          <h6>overflow</h6>
overflow가 2가지 상황이라는게 어떤 말씀이신가요?!
잘 이해가 가지 않는군요🥲

2023-07-08 07:35 UTC, ashleysyheo commented on src/components/Tabs/Tabs.tsx
> +export interface TabsProps extends ComponentPropsWithRef<'div'> {}
저도 후자가 좋아요 ㅎㅎㅎ 저렇게 `{}` 괄호 안에 아무것도 없으면 그냥 type을 사용하는 것도 좋을 것 같아요!

2023-07-08 07:36 UTC, ashleysyheo commented on src/stories/Tabs.stories.tsx
> +          <h6>overflow</h6>
아 그 block일 때 overflow 하나, outline일 때 overflow 하나요! 지금은 섞여 있어서 뭔가 시각적으로 살짝 헷갈려서요!!

2023-07-08 07:37 UTC, ashleysyheo commented on src/components/ToggleGroup/ToggleGroup.style.ts
> +    width: 'fit-content',
오오오오오오 짱인데요

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Checkbox/Checkbox.style.ts
> +  display: 'none',
css 순서 🫣

```js
display: 'none'

padding: 0
```

(저도 정말 정말 많이 헷갈려요......)

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Tab/Tab.style.ts
> +export type TabSelectedStylingProps = 'outline' | 'block';
이렇게 variant 종류 정의를 `.style.ts`에 넣는 거랑 컴포넌트 파일에 넣은 다음에 `.style.ts`에 임포트 해서 사용하는 것들 중에서 어떤 것을 더 선호하세요?

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Tab/Tab.style.ts
> +    borderBottom: `1px solid ${Theme.color.blue600}`,
css 순서! 레이아웃이랑 Box 사이 개행 부탁합니다~

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Toggle/Toggle.style.ts
> +
css 순서...

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Toggle/Toggle.style.ts
> +export const getUnSelectedToggleStyling = css({
갑자기 드는 생각

저희 모두 다 지금 emotion 스타일 네이밍 할 때 `*--style` vs `*--styling` 그리고 `get--*` 유무 이렇게 조금 서로 다 혼재되어 있는데, 이 부분도 통일하면 좋을 것 같아요!

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/ToggleGroup/ToggleGroup.tsx
> +import { ToggleGroupContainerStyling } from './ToggleGroup.style';
상대경로 임포트....

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/ToggleGroup/ToggleGroup.style.ts
> +import { Theme } from '@/styles/Theme';
경로...

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Toggle/Toggle.tsx
> +import { getSelectedToggleStyling, getUnSelectedToggleStyling } from './Toggle.style';
상대 경로...

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Tabs/Tabs.tsx
> +import { TabsContainerStyling } from './Tabs.style';
상대경로...

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Tabs/Tabs.style.ts
> +import { Theme } from '@/styles/Theme';
경로...

2023-07-08 07:57 UTC, ashleysyheo commented on src/components/Tab/Tab.tsx
> +
경로들...

2023-07-08 07:57 UTC, ashleysyheo commented on src/stories/ToggleGroup.stories.tsx
> +import Toggle from '@/components/Toggle/Toggle';
경로 `@components/Toggle/Toggle`로 변경해 주세요!

2023-07-08 08:25 UTC, Dahyeeee reviewed
고생많았어요 슬링키~~ 
소소한 리뷰... 내놓습니당

2023-07-08 08:25 UTC, Dahyeeee commented on src/components/Toggle/Toggle.tsx
> +  );
Tab에서처럼 삼항연산자로 반환해주면 일관성 있을 것 같아요!

2023-07-08 08:25 UTC, Dahyeeee commented on src/components/ToggleGroup/ToggleGroup.style.ts
> +export const ToggleGroupContainerStyling = () => {
함수 말고 그냥 css객체로 export 해도 될듯요?!

2023-07-08 08:25 UTC, Dahyeeee commented on src/components/Toggle/Toggle.style.ts
> +export const getUnSelectedToggleStyling = css({
동의합니당

2023-07-08 11:24 UTC, dladncks1217 reviewed
남은 피드백들 반영해 보았습니다~!

2023-07-08 11:24 UTC, dladncks1217 commented on src/components/Toggle/Toggle.style.ts
> +
개행이 하나 더 들어갔군요 ㅎㅎ..

2023-07-08 11:24 UTC, dladncks1217 commented on src/components/Toggle/Toggle.style.ts
> +export const getUnSelectedToggleStyling = css({
좋습니당

2023-07-08 11:24 UTC, dladncks1217 commented on src/components/Toggle/Toggle.tsx
> +  );
좋습니다👍
```
return selected ? (
    <>
      <div css={getSelectedToggleStyling} {...attributes} ref={ref}>
        {text}
      </div>
    </>
  ) : (
    <>
      <div css={getUnSelectedToggleStyling} {...attributes} ref={ref}>
        {text}
      </div>
    </>
  );
```
이렇게 반영 해 보겠습니다!

2023-07-08 11:24 UTC, dladncks1217 commented on src/components/ToggleGroup/ToggleGroup.style.ts
> +export const ToggleGroupContainerStyling = () => {
좋습니다👍

2023-07-08 11:24 UTC, dladncks1217 commented on src/stories/Tabs.stories.tsx
> +          <h6>overflow</h6>
아하 그 말씀이셨군요!
추가하겠습니다~!

2023-07-09 08:21 UTC, ashleysyheo approved these changes
슬링키 고생하셨습니다!!!!!!! 👍

임포트 경로만 한 번 더 확인해 주세요!

2023-07-09 08:21 UTC, ashleysyheo commented on src/components/Tabs/Tabs.tsx
> +import { getTabsContainerStyling } from './Tabs.style';
경로...!!!

2023-07-09 08:21 UTC, ashleysyheo commented on src/components/ToggleGroup/ToggleGroup.style.ts
> +import { Theme } from '@/styles/Theme';
경로 한 번만 더 확인해 주세요!

2023-07-09 08:25 UTC, Dahyeeee commented on src/stories/ToggleGroup.stories.tsx
> +            <Toggle text="ganada" />
ㅋㅋㅋㅋㅋ
haha ganada 웃겨서 좋긴한데 그냥 toggle1 toggle2같은 무난한 단어로 바꾸는 게 어떨까용?

2023-07-09 08:36 UTC, ashleysyheo commented on src/stories/ToggleGroup.stories.tsx
> +            <Toggle text="ganada" />
저도 동의합니다!

2023-07-09 09:52 UTC, dladncks1217 commented on src/stories/ToggleGroup.stories.tsx
> +            <Toggle text="ganada" />
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 수정하겠습니다

2023-07-09 10:32 UTC, Dahyeeee approved these changes
굳굳!! 슬링키도 짱짱맨

2023-07-09 11:54 UTC, merged