StarRating 컴포넌트 추가
hang-log-design-system/design-system pull request #20
Opened 2023-07-11 07:31 UTC by dladncks1217

## StarRating

<img width="345" alt="스크린샷 2023-07-11 오후 4 29 18" src="https://github.com/hang-log-design-system/design-system/assets/45068522/148e9db9-95dc-498b-be60-174418963720">
<img width="605" alt="스크린샷 2023-07-11 오후 4 29 05" src="https://github.com/hang-log-design-system/design-system/assets/45068522/3865442f-1bca-4229-b335-c9d96743aec1">

<br/>
<br/>

### StarRating 컴포넌트 사용 시 `useStarRating` 훅 사용이 필수입니다.

2023-07-11 07:56 UTC, ashleysyheo requested changes
수고하셨습니다 💯 역시 파워블러거 🔥

2023-07-11 07:56 UTC, ashleysyheo commented on .storybook/main.ts
> +    });
👍

2023-07-11 07:56 UTC, ashleysyheo commented on src/components/StarRating/StarRating.style.ts
> +      backgroundImage: `url(${HalfEmptyLeftStar})`,
css 순서?? backgroundImage 위에 개행해 주세요

2023-07-11 07:56 UTC, ashleysyheo commented on src/components/StarRating/StarRating.style.ts
> +      backgroundImage: `url(${HalfEmptyRightStar})`,
css 순서!

2023-07-11 07:56 UTC, ashleysyheo commented on src/components/StarRating/StarRating.tsx
> +import { getStarRatingBoxStyling } from './StarRating.style';
상대경로.........

2023-07-11 07:56 UTC, ashleysyheo commented on src/stories/StarRating.stories.ts
> +import useStarRating from '@/components/StarRating/useStarRating';
경로.....

2023-07-11 07:56 UTC, ashleysyheo commented on src/components/StarRating/useStarRating.ts
> +import { MouseEvent, useCallback, useState } from 'react';
`MouseEvent` 타입 온리 임포트.........

2023-07-11 10:43 UTC, Dahyeeee requested changes
욜루 어려운거 해내셨네요 멋져용

2023-07-11 10:55 UTC, ashleysyheo commented on src/components/StarRating/StarRating.tsx
> +  gap?: number;
완벽하게 gap 사이즈가 비례적으로 변하지 않아서 값을 입력받는 것이 더 좋을 것 같아요!

2023-07-11 11:44 UTC, ashleysyheo commented on src/components/StarRating/StarRating.tsx
> +  rate: number;
아니면 jsdocs로!

2023-07-12 02:06 UTC, dladncks1217 commented on src/components/StarRating/StarRating.tsx
> +  rate: number;
오호 jscocs랑 0.5단위 좋네요! 반영하겠습니다👍

2023-07-12 02:06 UTC, dladncks1217 commented on src/components/StarRating/StarRating.tsx
> +  gap?: number;
저도 직접 입력이 더 좋은 것 같습니다!

2023-07-12 02:06 UTC, dladncks1217 commented on src/components/StarRating/StarRating.tsx
> +  const rateContainers = Array(10)
좋네요👍👍

2023-07-12 04:41 UTC, Dahyeeee approved these changes

2023-07-12 04:49 UTC, merged