Box, Center, Flex 컴포넌트 생성
hang-log-design-system/design-system pull request #21
Opened 2023-07-11 11:03 UTC by dladncks1217

## Flex
<img width="740" alt="스크린샷 2023-07-11 오후 8 01 31" src="https://github.com/hang-log-design-system/design-system/assets/45068522/25e80f6a-eeea-4320-94f6-40fcef15fe2f">

## Center

<img width="608" alt="스크린샷 2023-07-11 오후 8 01 53" src="https://github.com/hang-log-design-system/design-system/assets/45068522/0c1e504a-1d20-4266-9bac-992b2edb2776">

## Box
<img width="732" alt="스크린샷 2023-07-11 오후 8 02 20" src="https://github.com/hang-log-design-system/design-system/assets/45068522/c93bf132-e9fa-4e52-a073-2a5128ffaba6">

close #14

2023-07-11 11:43 UTC, ashleysyheo requested changes
진짜 진짜 수고 많았습니다 💯💯

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Box/Box.style.ts
> +import { Theme } from '@/styles/Theme';
경로!

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Box/Box.tsx
> +const Box = ({ styles = {}, children }: BoxProps, ref?: ForwardedRef<HTMLDivElement>) => {
Box에 ref가 필요할까요??

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Box/Box.tsx
> +import { ComponentPropsWithRef, ForwardedRef, forwardRef } from 'react';
ComponentPropsWithRef랑 ForwardedRef는 타입 온리 임포트

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Center/Center.tsx
> +import { ComponentPropsWithRef, ForwardedRef, forwardRef } from 'react';
ComponentPropsWithRef랑 ForwardedRef는 타입 온리 임포트

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Center/Center.tsx
> +const Center = ({ children }: CenterPorps, ref?: ForwardedRef<HTMLDivElement>) => {
여기도 ref가 필요할까요??

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Flex/Flex.style.ts
> +  height?: string;
🔥

2023-07-11 11:43 UTC, ashleysyheo commented on src/components/Flex/Flex.tsx
> +import { ComponentPropsWithRef, ForwardedRef, forwardRef } from 'react';
ComponentPropsWithRef랑 ForwardedRef는 타입 온리 임포트

2023-07-11 11:43 UTC, ashleysyheo commented on src/stories/Box.stories.tsx
> +      backgroundColor: 'red',
작은 부탁... 색깔 `Theme.color.blue500`...? 🙏

2023-07-11 11:43 UTC, ashleysyheo commented on src/stories/Flex.stories.tsx
> +        >
색깔 빨파초..🫣😂 너무 쨍해요... ㅋㅋㅋ

Theme.color.blue500, Theme.color.red300, Theme.color.green 그리고 color Theme.color.white으로 해주세요! 🙇🏻‍♀️

2023-07-11 12:39 UTC, Dahyeeee approved these changes
아주 유용한 플랙스와 박스~~
감사합니다 슬링키 :)

2023-07-11 12:39 UTC, Dahyeeee commented on src/components/Flex/Flex.style.ts
> +  height?: string;
와우와우!!

2023-07-12 01:52 UTC, dladncks1217 commented on src/components/Flex/Flex.tsx
> +const Flex = ({ styles = {}, children }: FlexPorps, ref?: ForwardedRef<HTMLDivElement>) => {
좋습니다👍👍

2023-07-12 01:52 UTC, dladncks1217 commented on src/stories/Box.stories.tsx
> +      backgroundColor: 'red',
ㅋㅋㅋㅋㅋㅋㅋㅋ알겠습니다

2023-07-12 02:00 UTC, ashleysyheo commented on src/components/Box/Box.tsx
> +import type { ComponentPropsWithRef } from 'react';
ref를 안 사용하니까 `forwardRef`는 필요 없고, `ComponentPropsWithRef`도 `ComponentPropsWithoutRef`로 변경해 주세요!

2023-07-12 02:00 UTC, ashleysyheo commented on src/components/Center/Center.tsx
> +import type { ComponentPropsWithRef } from 'react';
ref를 안 사용하니까 `forwardRef`는 필요 없고, `ComponentPropsWithRef`도 `ComponentPropsWithoutRef`로 변경해 주세요!

2023-07-12 02:00 UTC, ashleysyheo commented on src/components/Flex/Flex.tsx
> +import type { ComponentPropsWithRef } from 'react';
ref를 안 사용하니까 `forwardRef`는 필요 없고, `ComponentPropsWithRef`도 `ComponentPropsWithoutRef`로 변경해 주세요!

2023-07-12 02:11 UTC, dladncks1217 commented on src/components/Box/Box.tsx
> +import type { ComponentPropsWithRef } from 'react';
오호.. `ComponentPropsWithoutRef` 라는 것도 있었군요!

2023-07-12 02:17 UTC, ashleysyheo approved these changes

2023-07-12 02:21 UTC, merged