Menu 컴포넌트 구현
hang-log-design-system/design-system pull request #22
Opened 2023-07-11 12:40 UTC by Dahyeeee

![image](https://github.com/hang-log-design-system/design-system/assets/102305630/84913a2d-31e0-4c6c-8161-01e9fd9bb0b7)

버튼을 컴포넌트 내부에 넣고 스타일도 받을 수 있게 했습니다.
태그나 아쉬운거 등등 알려주세요!!

close#9

2023-07-11 13:03 UTC, ashleysyheo requested changes
수고했습니다 헤다 👍

2023-07-11 13:03 UTC, ashleysyheo commented on src/components/Menu/Menu.tsx
> +}
문서화 한다는 의미에서 jsdocs를 추가해 주면 좋을 것 같아요!

2023-07-11 13:03 UTC, ashleysyheo commented on src/styles/Theme.ts
> +};
as const 추가해 주세요! 나중에 컴파일한 다음에 저희 행록 프로젝트에서 사용할 때 지금은 hover하면 아마 number 타입이라고만 알려줄걸요!

2023-07-11 13:03 UTC, ashleysyheo commented on src/components/Menu/Menu.style.ts
> +  zIndex: Theme.zIndex.overlayTop,
버튼이랑 메뉴 사이에 gap 8px (Theme.spacer.spacing2)

2023-07-11 13:03 UTC, ashleysyheo commented on src/components/Menu/Menu.style.ts
> +  width: '150px',
이건 minWidth으로 설정하면 좋을 것 같아요! 나중에 혹시 모를 엄청 긴 문자가 들어올 수도 있으니까요

2023-07-11 13:35 UTC, dladncks1217 approved these changes
고생 많으셨습니다 헤다 👍👍👍

2023-07-11 13:35 UTC, dladncks1217 commented on src/components/Menu/Menu.tsx
> +      <Button variant={titleVariant} onClick={toggleMenu}>
저도 애슐리 의견과 동일하게 버튼은 children으로 받는게 더 좋아보입니다!
내부 메뉴를 클릭했을 때 link 등의 기능도 넣으려면 컴포넌트들이 외부에서 주입되는게 더 좋아보여요😁

2023-07-11 13:35 UTC, dladncks1217 commented on src/stories/Menu.stories.tsx
> +      { name: '로그아웃', onClick: () => console.log('logout') },
별거 아니긴 합니다!

```
interface Menu {
  name: string;
  onClick: () => void;
}
```
onClick이 ()=> void인데, ()=>console.log()에서 console.log를 반환한다는게 뭔가 이상한 것 같아요!
console.log() 반환값이야 원래 없으니 별 문제는 없지만, 그냥 보기에 좀 더 명확하게 {} 를 써주는건 어떨까 싶기도 하네요!
꼭 콘솔이 들어가야할까 싶기도 하구요 ㅎㅎ...

2023-07-11 13:35 UTC, dladncks1217 commented on src/styles/Theme.ts
> +};
as const 좋네요👍

2023-07-11 13:35 UTC, dladncks1217 commented on src/components/Menu/Menu.style.ts
> +
`transition: 'all .2 ease-in'`
같은걸 추가해도 예쁠 것 같은데 어떤가요?!

2023-07-11 13:54 UTC, Dahyeeee commented on src/components/Menu/Menu.tsx
> +      <Button variant={titleVariant} onClick={toggleMenu}>
저도 버튼의 다른 속성들을 붙일 수 없는 한정적인것에 아쉬움이 있는데 
children으로 외부에서 컴포넌트를 받아오면 Menu를 사용해주는 곳에서 
메뉴창이 메뉴창바깥을 클릭했을 때 닫히는 기능을 구현해줘야하는 번거로움이 있어요!

내부메뉴클릭했을 때 이동하는 기능은 menu프롭스의 onClick으로 주입할 수 있게 하긴 했는데,

children으로 받고 사용하는 쪽에서 useMenu 훅을 만들어서 같이 사용하도록 할까요?

2023-07-11 14:07 UTC, Dahyeeee commented on src/components/Menu/Menu.tsx
> +  const closeMenu = (e: MouseEvent) => {
음! 안해줘도 되던데 뭔가 잘못된걸까요?

2023-07-11 14:20 UTC, ashleysyheo commented on src/components/Menu/Menu.tsx
> +      <Button variant={titleVariant} onClick={toggleMenu}>
커스텀 훅 만든거 좋은 것 같아요! 나중에 훅도 따로 export해서 사용하는 측에서 훅도 사용하도록 하면 되니까요!!

2023-07-11 14:25 UTC, ashleysyheo commented on src/components/Menu/Menu.tsx
> +    if (!menuRef.current?.contains(e.target as Node)) {
오호! 그럼 as 를 사용하는 대신 위에서 조거문으로 처리해줄 수도 있지 않나요?

2023-07-11 14:26 UTC, ashleysyheo commented on src/components/Menu/Menu.tsx
> +  const closeMenu = (e: MouseEvent) => {
어... 몰라요! ㅋㅋㅋ 저는 매번 린트 에러가 떴었거든요 🧐

방금 MouseEvent 타입을 임포트하니까 아래 에러가 떠요!
```
No overload matches this call.
  Overload 1 of 2, '(type: "click", listener: (this: Window, ev: MouseEvent) => any, options?: boolean | AddEventListenerOptions | undefined): void', gave the following error.
    Argument of type '(e: MouseEvent<HTMLElement>) => void' is not assignable to parameter of type '(this: Window, ev: MouseEvent) => any'.
      Types of parameters 'e' and 'ev' are incompatible.
        Type 'MouseEvent' is not assignable to type 'MouseEvent<HTMLElement, MouseEvent>'.
  Overload 2 of 2, '(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions | undefined): void', gave the following error.
    Argument of type '(e: MouseEvent<HTMLElement>) => void' is not assignable to parameter of type 'EventListenerOrEventListenerObject'.ts(2769)
const closeMenu: (e: MouseEvent<HTMLElement>) => void
```

뭔지 한 번 보면 좋을 것 같아요!

2023-07-12 04:44 UTC, ashleysyheo approved these changes

2023-07-12 04:44 UTC, ashleysyheo commented on src/components/Menu/Menu.style.ts
> +export const MenuStyling = css({});
소문자.......

2023-07-12 05:03 UTC, merged