FloatingButton, Skeleton, RadioButton 구현
hang-log-design-system/design-system pull request #3
Opened 2023-07-08 09:17 UTC by Dahyeeee

RadioButton에서 글씨클릭으로 버튼클릭이 안됩니당...
배포전까지 수정해보도록 하겠습니다 ㅠㅠ

스켈레톤은 저 정도면 되려나요? 

여러분에 비해서 코드를 적게 작성한 것 같군요. 분발하겠습니당

2023-07-08 09:46 UTC, ashleysyheo requested changes
헤다 정말 수고 많았습니다!!!! 

#### 절대 경로
임포트 경로들 다시 한 번 확인 부탁드려요

#### 커밋
커밋 중간에 draft가 있는데 이거 revert(?) 아니면 이름 수정해 주세요. 저희가 막 때린 커밋이어서요...

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/FloatingButton/FloatingButton.style.ts
> +        stroke: 'white',
theme에 있는 white 색상 이용해 주세요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/FloatingButton/FloatingButton.style.ts
> +        stroke: 'black',
마찬가지로 theme에 있는 색상 사용해 주세요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/FloatingButton/FloatingButton.tsx
> +} from './FloatingButton.style';
상대경로....

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/FloatingButton/FloatingButton.style.ts
> +export const FloatingButtonStyling = css({
저희 변수는 `camelCase`로 통일하기로 했어요

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Input/Input.style.ts
>    return style[size];
이건 왜 삭제된건가요??

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.tsx
> +            <input type="radio" hidden id={option} name={attributes.name} />
여기서도 다른 attributes를 받아올 가능성이 있지 않을까요? 그럼 FloatingButton에서 한 것처럼 `{ ...attributes }`를 해줘야 할 것 같아요.

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.tsx
> +            <label htmlFor={option} css={labelStyle}></label>
이 label의 목적은 무엇인가요? 밑에 `p` 태그 대신 라벨에 option 텍스트를 넣어도 되지 않나요? 그럼 글씨 클릭해서 라디오 버튼도 클릭할 수 있을 것 같아요

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Skeleton/Skeleton.style.ts
> +    animation: `${skeletonAnimation} 5s infinite ease-out`,
css 순서....!

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Skeleton/Skeleton.style.ts
> +    background: 'linear-gradient(-90deg, #aaa, #f0f0f0, #aaa, #f0f0f0)',
이것도 Theme에 있는 색상 사용하면 좋을 것 같아요! `gray100`이랑 `gray200` 어떠세요?

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Skeleton/Skeleton.style.ts
> +import { Theme } from '@/styles/Theme';
경로...

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.tsx
> +} from './RadioButton.style';
경로...

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Skeleton/Skeleton.tsx
> +const Skeleton = ({ width = '100%', height = '20px' }: SkeletonProps) => {
지금 medium 텍스트의 lineHeight가 24px이거든요, 그래서 이거에 맞춰서 default height를 설정하면 좋을 것 같아요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/Spinner/Spinner.style.ts
> -
?

2023-07-08 09:46 UTC, ashleysyheo commented on src/index.tsx
> +);
저희 index.tsx는 나중에 npm 배포할 때 컴포넌트들 export 할 때 사용할 것이어서, 커밋을 굳이 안 해도 될 것 같아요. 어떻게 생각하세요?

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/FloatingButton.stories.tsx
> +import FloatingButton from '@/components/FloatingButton/FloatingButton';
경로들...!

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/FloatingButton.stories.tsx
> +import { FloatingButtonProps } from '@/components/FloatingButton/FloatingButton';
타입 온리 임포트!

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/RadioButton.stories.tsx
> +import RadioButton from '@/components/RadioButton/RadioButton';
경로!

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/RadioButton.stories.tsx
> +    supportingText: 'supporting Text',
`Supporting text` 대소문자 바꿔주세요

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/FloatingButton/FloatingButton.style.ts
> +
FloatingButton도 transition 넣어주세요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/RadioButton.stories.tsx
> +export const Playground: Story = {};
스토리에 사용 케이스를 더 보여주면 좋을 것 같아요.

그냥 라디오 버튼들만 있을 때, 라벨이랑 있을 때, supportingText만 있을 때, 그리고 라벨이랑 supportingText 둘 다 있을 때.

굳이 addon으로 조작 안해도 이렇게 사용할 수 있다고 보여주면 좋을 것 같아요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.style.ts
> +    color: Theme.color.gray800,
텍스트 스타일 한 번 수정 부탁드립니다...🙇🏻‍♀️ 그냥 다 `Theme.color.gray800`으로 통일하는 게 더 자연스러운 것 같아요!

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +    height: '30px',
지금 조금 작아 보이는 것 같아요! `width: 500px` `height: 24px` 어떠세요?

2023-07-08 09:46 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +export const Playground: Story = {};
Playground 이외에 좀 더 다양한 사용 케이스 스토리를 보여주면 좋을 것 같아요! 피그마에 있는 것처럼 실사용 케이스들을 보여주는 건 어떠세요??

2023-07-08 12:31 UTC, dladncks1217 reviewed
주말인데 고생 많으셨어요 헤다~! 👏👏💯💯💯
애슐리가 리뷰 많이 남겨주셔서 저는 상대적으로 남길 게 적더군요😅
아래 내용 하나만 확인 부탁드릴게요~


## Floating Button에서 피그마와 스토리북이 일치하지 않는 문제
이게 제 컴퓨터에서만 그렇게 보이는건진 모르겠는데, 아래와 같이 조금 달라보이더라구요🥲
확인해보시면 좋을 것 같아요!

### 피그마
<img width="348" alt="스크린샷 2023-07-08 오후 9 23 23" src="https://github.com/hang-log-design-system/design-system/assets/45068522/3ab42259-b2af-4b81-a815-ea3bf19aad9c">
<br/>

### 스토리북
<img width="89" alt="스크린샷 2023-07-08 오후 9 19 23" src="https://github.com/hang-log-design-system/design-system/assets/45068522/2c483ec4-ad26-49c4-8261-88492c2da268">

2023-07-08 12:31 UTC, dladncks1217 commented on src/index.tsx
> +);
저도 동일한 생각입니다! 
아마 예전에 페어로 작업했던 게 한꺼번에 같이 올라온 것 같은데, 맞을까요?!

2023-07-08 12:31 UTC, dladncks1217 commented on src/stories/Skeleton.stories.tsx
> +export const Playground: Story = {};
좋은 것 같습니다👍

2023-07-09 06:05 UTC, Dahyeeee commented on src/components/Spinner/Spinner.style.ts
> -
..? ㅋㅋㅋ되돌렸습니다

2023-07-09 06:05 UTC, Dahyeeee commented on src/components/RadioButton/RadioButton.tsx
> +            <label htmlFor={option} css={labelStyle}></label>
그러면 css가 깨져서 버튼이랑 텍스트가 겹치더라구요 ㅠㅠㅠㅠㅠㅠ 
지금은 label이 버튼모양을 생성해주고 있어서 그런 것 같은데 배포전까지 해결해볼게요!!

2023-07-09 06:05 UTC, Dahyeeee commented on src/components/RadioButton/RadioButton.tsx
> +            <input type="radio" hidden id={option} name={attributes.name} />
맞아요! 저도 동의하는데 어디 태그에 줘야할지 애매해서 일단 안줬어요. input에 주면 되겠지요..?

2023-07-09 06:05 UTC, Dahyeeee commented on src/components/Input/Input.style.ts
>    return style[size];
ㅠㅠ 되돌렸습니당

2023-07-09 08:06 UTC, Dahyeeee commented on src/components/FloatingButton/FloatingButton.style.ts
> +import { Theme } from '@/styles/Theme';
+버튼 깨지는거 수정했습니다! 감사합니당~

2023-07-09 08:22 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.tsx
> +            <input type="radio" hidden id={option} name={attributes.name} />
그러면 되지 않을까요...? 흠... 근데 이건 나중에 사용하면서 재차 확인이 필요하긴 하겠네요. 🤔

2023-07-09 08:27 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +export const Playground: Story = {};
다양한 사용 케이스라는 의미가 아래 이미지처럼 이렇게 조합할 수 있다를 보여주는 것을 말했어요!

<img width="1280" alt="Skeleton" src="https://github.com/hang-log-design-system/design-system/assets/51967731/49ffee89-37e3-4aaa-9c59-974d8c533372">

2023-07-09 08:33 UTC, ashleysyheo reviewed
수고 많았습니다 헤다!! 👍

질문 있어요!! 

저희 styling으로 통일하는 건가요?? ㅎㅎㅎ

2023-07-09 08:33 UTC, ashleysyheo commented on src/components/RadioButton/RadioButton.tsx
> +  supportingText?: string;
jsdoc으로 options에 대한 설명을 추가해 주면 좋을 것 같아요! 정확히 뭘 넘겨주는지를 알려주면 더 도움이 될 것 같아요

2023-07-09 08:33 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +  },
굳이 width height control까지 disabled 시킬 필요가 있을까요?? 아래도 마찬가지에요!

2023-07-09 08:33 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +    variant: { control: false },
variant만 control false해도 되지 않을까요??

그런데 circle 과 관련해서 질문이 있습니다! 만약 width height를 다르게 입력하면 타원으로 나오는 건가요?

2023-07-09 08:35 UTC, Dahyeeee commented on src/stories/Skeleton.stories.tsx
> +export const Playground: Story = {};
아하! 그것도 추가할게요

2023-07-09 08:47 UTC, Dahyeeee commented on src/stories/Skeleton.stories.tsx
> +    variant: { control: false },
네 타원이 나옵니다 ㅋㅋㅋㅋ 음 circle일때는 width로 height를 통일시켜줄까요?
우리가 타원을 쓸일이... 있을까요? ㅎㅎㅎ

2023-07-09 08:47 UTC, Dahyeeee commented on src/components/RadioButton/RadioButton.tsx
> +  supportingText?: string;
애슐리꺼 참고해서 추가해볼게요!

2023-07-09 09:18 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +    variant: { control: false },
없지 않을까요....? ㅎㅎㅎ

2023-07-09 10:41 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +  render: ({}) => {
필요없는 중괄호!

2023-07-09 10:41 UTC, ashleysyheo commented on src/stories/Skeleton.stories.tsx
> +  render: ({}) => {
여기서는 width, height, variant 앤드온을 조작해도 아무런 변화가 없으니까 control을 false로 설정하면 좋을 것 같아요!

2023-07-09 10:41 UTC, Dahyeeee commented on src/stories/Skeleton.stories.tsx
> +    variant: { control: false },
width로 height설정해주도록 변경했습니다~~

2023-07-09 10:41 UTC, Dahyeeee commented on src/stories/Skeleton.stories.tsx
> +export const Playground: Story = {};
combination으로 추가했습니다. 써놓고 보니 피자 종류같군요

2023-07-09 10:44 UTC, Dahyeeee commented on src/components/RadioButton/RadioButton.tsx
> +            <input type="radio" hidden id={option} name={attributes.name} />
일단 인풋에 주었습니다! Tab처럼 RadioGroup이랑 Radio를 따로 만들어야 하나 고민이 되긴 하네요

2023-07-09 11:55 UTC, Dahyeeee commented on src/components/RadioButton/RadioButton.tsx
> +            <label htmlFor={option} css={labelStyle}></label>
해결해서 반영했습니다 얄루

2023-07-09 12:07 UTC, ashleysyheo approved these changes

2023-07-09 12:07 UTC, ashleysyheo reviewed
헤다 짱짱짱이에여 💯❗️👍

2023-07-10 03:57 UTC, dladncks1217 approved these changes

2023-07-10 03:58 UTC, merged